### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/.github#6]
Use the [code of conduct from our Playbook](https://playbook.voorhoede.nl/organisation/code-of-ethics-and-professional-conduct.html)?

See [https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project).

**Comment by Siilwyn** [comment]
Moved to trello https://trello.com/c/vqIV7kaI/10-code-of-conduct
